# Generated by Django 5.0.1 on 2024-01-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_remove_reservation_client_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateTimeField(),
        ),
    ]
