# Generated by Django 5.0.1 on 2024-01-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_alter_reservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
